import {Profile,SocialLinks,Metrics,UI,Experience,Skills,Projects,HardwareProjects,AIStory,Education,Credentials} from './content.js';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(name,url,cls='')=>`<a class="${cls}" href="${e(url)}" target="_blank" rel="noopener noreferrer">${e(name)} <span aria-hidden="true">↗</span></a>`;
document.querySelector('#app').innerHTML=`<header class="header"><a class="brand" href="#home"><span class="monogram">${Profile.initials}<i></i></span><span>${Profile.shortName}<small>ENGINEERING PORTFOLIO</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" aria-label="Main navigation">${UI.nav.map(([n,id])=>`<a href="#${id}">${n}</a>`).join('')}</nav><a class="nav-contact" href="#contact">Let’s connect ↗</a></header><main><section id="home" class="hero wrap"><div class="hero-copy"><div class="eyebrow"><span class="signal"></span> SYSTEMS × AUTOMATION × INTELLIGENCE</div><p class="hero-name">${Profile.name}</p><h1>${Profile.heroTitle[0]}<br><span>${Profile.heroTitle[1]}</span></h1><p class="headline">${Profile.headline}</p><p class="hero-statement">${Profile.statement}</p><div class="role"><span>↳</span> <span id="role">${Profile.roles[0]}</span></div><div class="hero-actions"><a class="button primary" href="#experience">Explore My Work <span>↗</span></a><a class="button" href="#projects">View Projects <span>↗</span></a></div><div class="social-row">${SocialLinks.slice(0,2).map(s=>link(s.name,s.url)).join('')}<button id="resume" class="text-button">Download Resume ↓</button><a href="#contact">Contact Me ↗</a></div></div><div class="hero-system"><div class="system-top"><span>ENGINEERING SYSTEM / 01</span><button id="motion" aria-pressed="false">Pause motion</button></div><canvas id="constellation" tabindex="0" role="img" aria-label="Three-dimensional engineering network. Use arrow keys or drag to rotate."></canvas><div class="system-core"><span>ENGINEERING</span><strong>Reliable<br>by design.</strong><small>BUILD · VALIDATE · EVOLVE</small></div><div class="system-bottom"><span>DRAG / ARROW KEYS</span><span>${Profile.heroNodes.length} CONNECTED TECHNOLOGIES</span></div></div><div class="hero-foot"><span>Based in ${Profile.location}</span><a href="#about">Discover the engineering behind the work ↓</a></div></section><div class="metric-strip wrap">${Metrics.slice(0,4).map(m=>`<div><strong>${m.value}</strong><span>${m.label}</span></div>`).join('')}</div><div id="sections"></div></main><footer class="wrap"><span>© ${new Date().getFullYear()} ${Profile.shortName}</span><span>${UI.footer}</span><a href="#home">Back to top ↑</a></footer>`;
document.querySelector('.menu-toggle').onclick=ev=>{const open=ev.currentTarget.getAttribute('aria-expanded')!=='true';ev.currentTarget.setAttribute('aria-expanded',String(open));document.querySelector('nav').classList.toggle('open',open);};
document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>{document.querySelector('nav').classList.remove('open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false');});
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let paused=reduced;
document.querySelector('#motion').setAttribute('aria-pressed',String(paused));
document.querySelector('#motion').textContent=paused?'Resume motion':'Pause motion';
document.querySelector('#motion').onclick=ev=>{paused=!paused;ev.currentTarget.textContent=paused?'Resume motion':'Pause motion';ev.currentTarget.setAttribute('aria-pressed',String(paused));document.body.classList.toggle('motion-paused',paused);};
let roleIndex=0;setInterval(()=>{if(!paused&&!document.hidden)document.querySelector('#role').textContent=Profile.roles[++roleIndex%Profile.roles.length];},3500);
const canvas=document.querySelector('canvas'),ctx=canvas.getContext('2d');
let width=500,height=530,angle=.35,pitch=-.18,drag=false,lastX=0,lastY=0,visible=true;
const nodes=Profile.heroNodes.map((name,i)=>{const y=1-2*(i+.5)/Profile.heroNodes.length,r=Math.sqrt(1-y*y),a=i*2.39996;return {name,x:Math.cos(a)*r,y,z:Math.sin(a)*r};});
new ResizeObserver(entries=>{const r=entries[0].contentRect;width=r.width;height=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=width*d;canvas.height=height*d;ctx.setTransform(d,0,0,d,0,0);}).observe(canvas);
new IntersectionObserver(entries=>visible=entries[0].isIntersecting).observe(canvas);
canvas.onpointerdown=ev=>{drag=true;lastX=ev.clientX;lastY=ev.clientY;canvas.setPointerCapture(ev.pointerId);};
canvas.onpointermove=ev=>{if(drag){angle+=(ev.clientX-lastX)*.006;pitch+=(ev.clientY-lastY)*.004;lastX=ev.clientX;lastY=ev.clientY;}};canvas.onpointerup=canvas.onpointercancel=()=>drag=false;
canvas.onkeydown=ev=>{if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown"].includes(ev.key)){ev.preventDefault();if(ev.key==="ArrowLeft")angle-=.12;if(ev.key==="ArrowRight")angle+=.12;if(ev.key==="ArrowUp")pitch-=.12;if(ev.key==="ArrowDown")pitch+=.12;}};let last=0;function frame(t){requestAnimationFrame(frame);if(!visible||document.hidden||t-last<32)return;const dt=Math.min(t-last,50);last=t;if(!paused&&!drag)angle+=dt*.000055;ctx.clearRect(0,0,width,height);const radius=Math.min(width*.36,height*.37);const viewAngle=angle+(paused?0:Math.min(scrollY,innerHeight)*.0008);const points=nodes.map(n=>{let x=n.x*Math.cos(viewAngle)+n.z*Math.sin(viewAngle),z=n.z*Math.cos(viewAngle)-n.x*Math.sin(viewAngle),y=n.y*Math.cos(pitch)-z*Math.sin(pitch);z=n.y*Math.sin(pitch)+z*Math.cos(pitch);const scale=1/(1+z*.24);return {...n,x:width/2+x*radius*scale,y:height/2+y*radius*scale,z,scale};});
ctx.lineWidth=.7;for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++){const a=nodes[i],b=nodes[j];if(Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z)<1.04){ctx.strokeStyle=`rgba(96,193,213,${.1+(2-points[i].z-points[j].z)*.055})`;ctx.beginPath();ctx.moveTo(points[i].x,points[i].y);ctx.lineTo(points[j].x,points[j].y);ctx.stroke();}}
points.sort((a,b)=>b.z-a.z).forEach((p,i)=>{const ai=p.name==='AI'||p.name==='LLMs',alpha=.52+(1-p.z)*.24;ctx.fillStyle=ai?`rgba(178,151,255,${alpha})`:`rgba(121,231,230,${alpha})`;ctx.shadowColor=ai?'#aa85ff':'#6de5e4';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(p.x,p.y,ai?5:3,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.font=`${ai?'600':'400'} 12px ui-monospace,monospace`;const tw=ctx.measureText(p.name).width;const tx=Math.max(8,Math.min(width-tw-8,p.x-tw/2));ctx.fillStyle='rgba(8,13,21,.84)';ctx.fillRect(tx-5,p.y+9,tw+10,21);ctx.fillStyle=`rgba(210,228,240,${alpha})`;ctx.fillText(p.name,tx,p.y+24);});}requestAnimationFrame(frame);
await import('./sections.js');

await import('./enhancements.js');
