import {Portrait,Organizations,TechnologyBadges,Credentials,Skills,Showcase,Experience,Education} from './content.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=(src,alt,cls='')=>src.endsWith('/thinkround.png')?`<span class="thinkround-symbol"><img src="${esc(src)}" alt="${esc(alt)}" loading="lazy" decoding="async"></span>`:`<img src="${esc(src)}" alt="${esc(alt)}" class="${cls}" loading="lazy" decoding="async">`;
const org=n=>Organizations.find(x=>x.name===n);
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const motionButton=document.querySelector('#motion');
const moving=()=>!reduced.matches&&motionButton.getAttribute('aria-pressed')!=='true';
const core=document.querySelector('.system-core');core.classList.add('portrait-core');
core.innerHTML=`<div class="portrait-frame"><img src="${esc(Portrait.image)}" alt="${esc(Portrait.alt)}" fetchpriority="high" width="650" height="867"><div class="portrait-shine"></div></div><div class="portrait-caption"><strong>${esc(Portrait.caption)}</strong><small>${esc(Portrait.detail)}</small></div><span class="portrait-corner corner-a"></span><span class="portrait-corner corner-b"></span>`;
document.querySelector('.hero-system').insertAdjacentHTML('beforeend','<div class="depth-orbit depth-orbit-one" aria-hidden="true"></div><div class="depth-orbit depth-orbit-two" aria-hidden="true"></div>');
document.querySelector('.about-signature .monogram').outerHTML=asset(Portrait.image,Portrait.caption,'signature-portrait');
document.querySelectorAll('.experience-title').forEach((el,i)=>{const o=org(Experience[i].company);if(o)el.insertAdjacentHTML('afterbegin',`<a class="organization-mark ${o.name==='ALSO'?'also-mark':''}" href="${o.url}" target="_blank" rel="noopener noreferrer" aria-label="${esc(o.name)} website">${asset(o.image,o.name+' logo')}</a>`);});
document.querySelectorAll('.education-grid article').forEach((el,i)=>{const o=org(Education[i].school);if(o)el.insertAdjacentHTML('afterbegin',`<a class="education-mark" href="${o.url}" target="_blank" rel="noopener noreferrer" aria-label="${esc(o.name)} website">${asset(o.image,o.name+' logo')}</a>`);});
const teamNames=Experience.map(x=>x.company);
document.querySelector('.metric-strip').insertAdjacentHTML('afterend',`<div class="team-ribbon wrap"><span>ENGINEERING ACROSS</span><div>${teamNames.map(n=>{const o=org(n);return `<a href="#experience" title="${esc(n)}">${asset(o.image,o.name+' logo')}<span>${esc(o.name)}</span></a>`;}).join('')}</div></div>`);
document.querySelector('.achievement-grid').classList.add('with-showcase');
document.querySelector('.credentials').outerHTML=`<div class="showcase"><div class="showcase-heading"><span class="eyebrow">THE ENGINEERING COLLECTION</span><h3>${esc(Showcase.title)}</h3><p>${esc(Showcase.description)}</p></div><div class="showcase-tabs" role="tablist" aria-label="Engineering collection">${Showcase.tabs.map((name,i)=>`<button role="tab" id="collection-tab-${i}" aria-selected="${i===0}" aria-controls="collection-panel-${i}" tabindex="${i===0?'0':'-1'}" data-collection="${i}">${name}<small>${[Credentials.length,TechnologyBadges.length,teamNames.length][i]}</small></button>`).join('')}</div>
<div role="tabpanel" id="collection-panel-0" aria-labelledby="collection-tab-0"><p class="collection-note">${esc(Showcase.credentialNote)}</p><div class="credential-grid">${Credentials.map(c=>`<a class="credential-card depth-card" href="${esc(c.url)}" target="_blank" rel="noopener noreferrer" aria-label="View ${esc(c.name)} credential"><div class="credential-art">${c.badge?asset(c.badge,c.name+' badge'):c.issuer==='IBM'?asset('./assets/ibm.png','IBM logo'):`<span class="issuer-wordmark">${esc(c.issuer)}</span>`}</div><div class="credential-copy"><small>${esc(c.issuer)}</small><h4>${esc(c.name)}</h4><span>View credential <b>↗</b></span></div></a>`).join('')}</div></div>
<div role="tabpanel" id="collection-panel-1" aria-labelledby="collection-tab-1" hidden><p class="collection-note">${esc(Showcase.technologyNote)}</p><div class="technology-collection">${TechnologyBadges.map(t=>`<a class="technology-token depth-card" href="#skills">${asset(t.image,t.name+' logo')}<span>${esc(t.name)}</span></a>`).join('')}</div><div class="collection-skills">${Skills.map(s=>`<details><summary>${esc(s.name)}<span>+</span></summary>${s.context?`<p>${esc(s.context)}</p>`:''}<div class="tags">${s.items.map(n=>`<span>${esc(n)}</span>`).join('')}</div></details>`).join('')}</div></div>
<div role="tabpanel" id="collection-panel-2" aria-labelledby="collection-tab-2" hidden><p class="collection-note">${esc(Showcase.teamNote)}</p><div class="team-collection">${teamNames.map(n=>{const o=org(n),exp=Experience.find(x=>x.company===n);return `<a class="team-token depth-card" href="#experience"><div>${asset(o.image,o.name+' logo')}</div><h4>${esc(n)}</h4><p>${esc(exp.title)}</p><small>${esc(exp.dates)}</small></a>`;}).join('')}</div></div></div>`;
const tabs=[...document.querySelectorAll('[data-collection]')];
function tabSelect(i){tabs.forEach((t,j)=>{t.setAttribute('aria-selected',String(i===j));t.tabIndex=i===j?0:-1;document.querySelector('#collection-panel-'+j).hidden=i!==j;});if(moving())document.querySelector('#collection-panel-'+i).animate([{opacity:0,transform:'translate3d(0,18px,0)'},{opacity:1,transform:'translate3d(0,0,0)'}],{duration:450,easing:'cubic-bezier(.2,.8,.2,1)'});}
tabs.forEach((t,i)=>{t.onclick=()=>tabSelect(i);t.onkeydown=ev=>{let j=i;if(ev.key==='ArrowRight')j=(i+1)%tabs.length;else if(ev.key==='ArrowLeft')j=(i+tabs.length-1)%tabs.length;else if(ev.key==='Home')j=0;else if(ev.key==='End')j=tabs.length-1;else return;ev.preventDefault();tabSelect(j);tabs[j].focus();};});
document.body.insertAdjacentHTML('afterbegin','<div class="reading-progress" aria-hidden="true"><i></i></div><div class="ambient-grid" aria-hidden="true"></div>');
const revealTargets=[...document.querySelectorAll('.section-heading,.about-lead,.about-detail,.journey>div,.experience-date,.experience-content,.impact-grid article,.skills-layout,.project-card,.ai-intro>div,.ai-intro>p,.ai-flow li,.education-grid article,.award,.showcase,.contact h2')];
revealTargets.forEach((el,i)=>{el.classList.add('motion-reveal');el.style.setProperty('--stagger',((i%3)*70)+'ms');});
const observer=new IntersectionObserver(entries=>{entries.forEach(({target,isIntersecting,boundingClientRect})=>{if(isIntersecting||!moving())target.classList.add('is-visible');else if(boundingClientRect.top>innerHeight+80||boundingClientRect.bottom<-80)target.classList.remove('is-visible');});},{threshold:.06,rootMargin:'40px 0px'});revealTargets.forEach(el=>observer.observe(el));
document.addEventListener('focusin',ev=>ev.target.closest('.motion-reveal')?.classList.add('is-visible'));
const chapters=[...document.querySelectorAll('.section')];let pending=false;
function drawScroll(){pending=false;const y=scrollY,h=innerHeight,max=Math.max(1,document.documentElement.scrollHeight-h);document.querySelector('.reading-progress i').style.transform=`scaleX(${Math.min(1,y/max)})`;const motion=moving();document.body.classList.toggle('motion-active',motion);if(!motion)return;
 document.documentElement.style.setProperty('--page-drift',Math.round(y*.03)+'px');
 const heroP=Math.min(y/h,1);core.style.setProperty('--portrait-y',(-heroP*32)+'px');core.style.setProperty('--portrait-turn',(heroP*-8)+'deg');
 for(const section of chapters){const r=section.getBoundingClientRect();if(r.bottom<0||r.top>h)continue;const progress=Math.max(-1,Math.min(1,(h*.5-r.top)/h));section.style.setProperty('--section-depth',(progress*-18)+'px');section.style.setProperty('--orbit-turn',(progress*30)+'deg');}
 const timeline=document.querySelector('.experience-list');const tr=timeline.getBoundingClientRect();timeline.style.setProperty('--timeline-progress',Math.max(0,Math.min(1,(h*.65-tr.top)/tr.height)));
}
function schedule(){if(!pending){pending=true;requestAnimationFrame(drawScroll);}}
addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);schedule();
const sync=()=>{if(!moving()){revealTargets.forEach(el=>el.classList.add('is-visible'));document.getAnimations().forEach(a=>a.cancel());}schedule();};
new MutationObserver(sync).observe(motionButton,{attributes:true,attributeFilter:['aria-pressed']});reduced.addEventListener('change',()=>{if(reduced.matches&&motionButton.getAttribute('aria-pressed')==='false')motionButton.click();sync();});sync();
document.querySelectorAll('.credential-card,.technology-token,.team-token,.education-grid article,.award').forEach(card=>{card.onpointermove=ev=>{if(ev.pointerType!=='mouse'||!moving())return;const r=card.getBoundingClientRect(),x=(ev.clientX-r.left)/r.width-.5,y=(ev.clientY-r.top)/r.height-.5;card.style.setProperty('--rx',(-y*7)+'deg');card.style.setProperty('--ry',(x*9)+'deg');card.style.setProperty('--glow-x',((x+.5)*100)+'%');card.style.setProperty('--glow-y',((y+.5)*100)+'%');};card.onpointerleave=()=>{card.style.setProperty('--rx','0deg');card.style.setProperty('--ry','0deg');};});
const scene=document.querySelector('.hero-system');scene.addEventListener('pointermove',ev=>{if(ev.pointerType!=='mouse'||!moving())return;const r=scene.getBoundingClientRect();core.style.setProperty('--pointer-x',(((ev.clientX-r.left)/r.width-.5)*9)+'deg');core.style.setProperty('--pointer-y',(-((ev.clientY-r.top)/r.height-.5)*7)+'deg');});scene.addEventListener('pointerleave',()=>{core.style.setProperty('--pointer-x','0deg');core.style.setProperty('--pointer-y','0deg');});
document.querySelectorAll('[data-filter],[data-skill]').forEach(el=>{const original=el.onclick;el.onclick=ev=>{if(!moving()||!document.startViewTransition){original(ev);return;}document.startViewTransition(()=>original(ev));};});
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',()=>{const target=document.getElementById(a.hash.slice(1));if(!target)return;target.querySelectorAll('.motion-reveal').forEach(x=>x.classList.add('is-visible'));const heading=target.querySelector('h2');if(heading&&moving())heading.animate([{opacity:.3,translate:'0 14px'},{opacity:1,translate:'0 0'}],{duration:650,easing:'cubic-bezier(.2,.8,.2,1)'});}));
document.querySelectorAll('.domain-list details,.hardware-archive,.education-grid details').forEach(d=>d.addEventListener('toggle',()=>{if(d.open&&moving()){const child=d.querySelector('.domain-body,.hardware-grid,.tags');child?.animate([{opacity:0,translate:'0 12px'},{opacity:1,translate:'0 0'}],{duration:400,easing:'ease-out'});}}));
