import {Profile,SocialLinks,Metrics,UI,Experience,Skills,Projects,HardwareProjects,AIStory,Education,Credentials} from './content.js';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=url=>{try{const u=new URL(url,location.href);return ['https:','http:','mailto:'].includes(u.protocol)?e(u.href):'';}catch{return '';}};
const link=(name,url,cls='')=>safeUrl(url)?`<a class="${cls}" href="${safeUrl(url)}" target="_blank" rel="noopener noreferrer">${e(name)} <span aria-hidden="true">↗</span></a>`:'';
const tags=items=>`<div class="tags">${items.map(s=>`<span>${e(s)}</span>`).join('')}</div>`;
const title=id=>`<div class="section-heading"><div class="eyebrow">${UI.sections[id][0]}</div><h2>${UI.sections[id][1]} ${UI.sections[id][2]?`<span>${UI.sections[id][2]}</span>`:''}</h2></div>`;
const flow=(items,cls='')=>`<ol class="flow ${cls}">${items.map((s,i)=>`<li><small>${String(i+1).padStart(2,'0')}</small><span>${e(s)}</span></li>`).join('')}</ol>`;
function visual(p,i){if(p.image&&safeUrl(p.image))return `<img class="project-image" src="${safeUrl(p.image)}" alt="${e(p.name)} project screenshot" loading="lazy">`;
 if(p.visual==='recommendation')return `<div class="project-visual recommendation"><div class="mini-label">EXPLAINABLE RECOMMENDATIONS</div><div class="rec-inputs"><span>Taste</span><span>Friends</span><span>Context</span></div><div class="rec-lines"></div><div class="rec-engine">RANKING ENGINE <span>↗</span></div><div class="rec-output"><span>01</span><div><i></i><i></i></div><span>Match</span></div><div class="mini-label bottom-label">PERSONAL SIGNALS → BETTER DISCOVERY</div></div>`;
 if(p.visual==='waveform')return `<div class="project-visual waveform"><div class="mini-label">SPEECH → SIGNAL → INSIGHT</div><div class="wave">${Array.from({length:48},(_,j)=>`<i style="--h:${12+Math.abs(Math.sin(j*.68)*Math.cos(j*.22))*72}%;--delay:${j*-.1}s"></i>`).join('')}</div><div class="wave-footer"><span>Transcribe</span><span>Detect</span><span>Score</span></div><div class="mini-label bottom-label">GOOGLE SPEECH RECOGNITION</div></div>`;
 if(p.visual==='dashboard')return `<div class="project-visual dashboard"><div class="mini-label">CONTRIBUTION SIGNALS / CONCEPT VIEW</div><div class="chart-bars">${[38,63,48,81,59,95,74,87].map((v,j)=>`<div style="--bar:${v}%"><i></i><span>${String(j+1).padStart(2,'0')}</span></div>`).join('')}</div><div class="mini-label bottom-label">COMPLEXITY · DELIVERY · RELIABILITY</div></div>`;
 return `<div class="secondary-visual"><span>${p.type==='Embedded'?'⌘':'◈'}</span><span>${e(p.category)}</span></div>`;
}
function project(p,i){return `<article class="project-card ${p.featured?'featured':''}" data-type="${e(p.type)}">${visual(p,i)}<div class="project-body"><div class="project-category">${e(p.category)}</div><h3>${e(p.name)}</h3><p>${e(p.description)}</p>${tags(p.technologies)}<div class="project-links"><button data-project="${i}" aria-haspopup="dialog">Explore project <span>↗</span></button>${link('View on GitHub',p.githubUrl)}</div></div></article>`;}
document.querySelector('#sections').innerHTML=`
<section id="about" class="section wrap">${title('about')}<div class="about-grid"><div class="about-lead"><p>${e(Profile.about[0])}</p><p>${e(Profile.secondary)}</p><div class="about-signature"><span class="monogram">PS<i></i></span><div>${e(Profile.name)}<small>${e(Profile.location)}</small></div></div></div><div class="about-detail">${Profile.about.slice(1).map(s=>`<p>${e(s)}</p>`).join('')}</div></div><div class="journey">${Profile.journey.map((s,i)=>`<div><small>0${i+1}</small><span>${e(s)}</span></div>`).join('')}</div><div class="telemetry"><span class="mini-label">HOW I CONNECT THE SYSTEM</span>${flow(Profile.pipeline)}</div></section>
<section id="experience" class="section wrap">${title('experience')}<div class="experience-list">${Experience.map((x,i)=>`<article class="experience"><div class="experience-date"><span class="timeline-dot ${x.current?'current':''}"></span><span>${e(x.dates)}</span>${x.current?'<small class="current-label">CURRENT ROLE</small>':''}<small>${e(x.location)}</small></div><div class="experience-content"><div class="experience-title"><h3>${e(x.company)}</h3><span class="experience-index">0${i+1}</span></div><h4>${e(x.title)}</h4><p>${e(x.description)}</p>${x.progression?`<div class="progression">${x.progression.map(s=>`<span>${e(s)}</span>`).join('<b>→</b>')}</div>`:''}<ul>${x.highlights.map(s=>`<li>${e(s)}</li>`).join('')}</ul>${tags(x.technologies)}${x.domains?`<div class="domain-list">${x.domains.map(d=>`<details><summary>${e(d.name)}<span aria-hidden="true">+</span></summary><div class="domain-body"><p>${e(d.description)}</p>${tags(d.tags)}${d.name==='Connectivity'?`<div class="packet-lab"><div class="lab-heading"><span>PACKET EXPLORER</span><span>Illustrative simulation</span></div><label>Protocol <select id="protocol"><option>Wi-Fi</option><option>Bluetooth</option><option>Ethernet</option></select></label><div class="packet-route"><span>Device</span><div><i></i><i></i><i></i></div><span>Access point</span><div><i></i><i></i></div><span>Service</span></div><output id="packet-output">Wi-Fi · Frame → Access point → IP network</output><p class="small">Trace the path from device traffic to network behavior. Protocol changes update the route below.</p></div>`:''}</div></details>`).join('')}</div>`:''}</div></article>`).join('')}</div></section>
<section id="impact" class="section impact-section"><div class="wrap">${title('impact')}<div class="impact-grid">${Metrics.map((m,i)=>`<article><span class="mini-label">0${i+1} / ${i===4?'BREADTH':'IMPACT'}</span><strong data-number="${e(m.value)}">${e(m.value)}</strong><h3>${e(m.label)}</h3><p>${e(m.detail)}</p></article>`).join('')}</div><div class="recognition-strip"><span class="award-icon">✧</span><strong>${e(UI.achievement)}</strong><span>Recognized at Amazon Lab126</span></div></div></section>
<section id="skills" class="section wrap">${title('skills')}<div class="skills-layout"><div class="skills-map"><div class="skills-orbit orbit-a"></div><div class="skills-orbit orbit-b"></div><div class="skills-center">ENGINEERING<small>SELECT A CLUSTER</small></div>${Skills.map((s,i)=>`<button class="skill-node node-${i} ${i===0?'selected':''}" data-skill="${i}" aria-pressed="${i===0}" aria-controls="skill-detail"><span class="node-symbol">${['✧','⌘','⌁','▣','⑂','◎','⌇'][i]}</span>${e(s.short)}</button>`).join('')}</div><div id="skill-detail" class="skill-detail" aria-live="polite"></div></div></section>
<section id="projects" class="section wrap">${title('projects')}<div class="projects-toolbar"><p>Public projects. Practical problems. Thoughtful engineering.</p><div class="filters" aria-label="Filter projects">${['All projects','AI & software','Embedded'].map((x,i)=>`<button data-filter="${e(x)}" aria-pressed="${i===0}" class="${i===0?'selected':''}">${e(x)}</button>`).join('')}</div></div><div class="projects-grid">${Projects.map(project).join('')}</div><details class="hardware-archive"><summary>Earlier explorations in hardware & wireless <span>7 projects +</span></summary><div class="hardware-grid">${HardwareProjects.map(p=>`<article><h3>${e(p.name)}</h3>${link('View on GitHub',p.githubUrl)}</article>`).join('')}</div></details><p id="filter-status" class="sr-only" aria-live="polite"></p></section>
<section id="ai-story" class="section ai-section"><div class="wrap"><div class="ai-intro"><div><div class="eyebrow">06 / THE NEXT CHAPTER</div><h2>${e(AIStory.title)}</h2></div><p>${e(AIStory.description)}</p></div>${flow(AIStory.stages,'ai-flow')}<div class="learning"><div><span class="eyebrow">EXPLORING NOW</span><p>Current learning & experimentation</p></div>${tags(AIStory.learning)}</div></div></section>
<section id="education" class="section wrap">${title('education')}<div class="education-grid">${Education.map(x=>`<article><span class="mini-label">${e(x.dates)}</span><h3>${e(x.degree)}</h3><p>${e(x.school)}</p>${x.coursework.length?`<details><summary>Relevant coursework <span>+</span></summary>${tags(x.coursework)}</details>`:''}</article>`).join('')}</div></section>
<section id="achievements" class="section wrap">${title('achievements')}<div class="achievement-grid"><article class="award"><span class="award-icon">✧</span><h3>${e(UI.achievement)}</h3><p>${e(UI.achievementText)}</p></article><div class="credentials"><span class="mini-label">AI & TECHNICAL CREDENTIALS</span>${Credentials.map((x,i)=>`<div><span>0${i+1}</span>${e(x.name)}</div>`).join('')}</div></div></section>
<section id="contact" class="section wrap contact"><div class="eyebrow">09 / LET’S CONNECT</div><h2>${e(Profile.contact)}</h2><p>${e(Profile.location)}</p><div class="contact-actions">${Profile.email?link('Email me',`mailto:${Profile.email}`,'button primary'):''}${SocialLinks.map(s=>link(s.name,s.url,'button')).join('')}</div>${Profile.email?`<a class="email" href="mailto:${e(Profile.email)}">${e(Profile.email)} ↗</a>`:''}</section>
<dialog id="project-dialog" aria-labelledby="dialog-title"><div class="dialog-header"><span class="mini-label">PROJECT DEEP DIVE</span><button class="close-dialog" aria-label="Close project details">✕</button></div><div id="dialog-body"></div></dialog>`;
function selectSkill(i){const s=Skills[i];document.querySelector('#skill-detail').innerHTML=`<span class="eyebrow">CLUSTER ${String(i+1).padStart(2,'0')} / 07</span><h3>${e(s.name)}</h3>${s.context?`<p class="learning-label">${e(s.context)}</p>`:'<p class="learning-label">Tools, technologies & engineering methods</p>'}${tags(s.items)}`;document.querySelectorAll('[data-skill]').forEach(b=>{const active=Number(b.dataset.skill)===i;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active));});}
selectSkill(0);document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>selectSkill(Number(b.dataset.skill)));
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{const filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});let count=0;document.querySelectorAll('.project-card').forEach(c=>{c.hidden=filter!=='All projects'&&c.dataset.type!==filter;if(!c.hidden)count++;});document.querySelector('.hardware-archive').hidden=filter==='AI & software';document.querySelector('#filter-status').textContent=`Showing ${count} ${filter.toLowerCase()} projects.`;});
const dialog=document.querySelector('dialog');let opener;
document.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>{opener=b;const p=Projects[Number(b.dataset.project)];document.querySelector('#dialog-body').innerHTML=`<div class="project-category">${e(p.category)}</div><h2 id="dialog-title">${e(p.name)}</h2><p>${e(p.description)}</p>${p.image?visual(p):''}<h3>Architecture</h3>${flow(p.architecture,'detail-flow')}<h3>Engineering details</h3><ul>${p.highlights.map(s=>`<li>${e(s)}</li>`).join('')}</ul><h3>Technologies</h3>${tags(p.technologies)}<h3>Key engineering concepts</h3>${tags(p.concepts)}${p.visual==='recommendation'?`<div class="interactive-demo"><h3>Explore the ranking signals</h3><p>Illustrative weights, not live recommendations.</p><label>Personal taste <input id="taste" type="range" min="10" max="80" value="50"><output id="taste-value">50%</output></label><div id="weight-bars"></div></div>`:p.visual==='dashboard'?`<div class="interactive-demo"><h3>Explore contribution dimensions</h3><p>Illustrative view, not live GitHub data.</p><label>Dimension <select id="dimension"><option>Complexity</option><option>Delivery</option><option>Reliability</option></select></label><output id="dimension-output">Complexity: examine the scope and difficulty of engineering work.</output></div>`:''}<div class="dialog-actions">${link('View on GitHub',p.githubUrl,'button primary')}${p.demoUrl?link('Open demo',p.demoUrl,'button'):''}</div>`;dialog.showModal();
 const taste=document.querySelector('#taste');if(taste){const update=()=>{const t=Number(taste.value);document.querySelector('#taste-value').value=t+'%';const rest=100-t;document.querySelector('#weight-bars').innerHTML=['Personal taste','Trusted friends','Availability','Context','Novelty'].map((x,i)=>{const val=i===0?t:rest*[.4,.25,.2,.15][i-1];return `<div class="weight-row"><span>${x}</span><i style="--weight:${val}%"></i><b>${Math.round(val)}%</b></div>`;}).join('');};taste.oninput=update;update();}
 const dim=document.querySelector('#dimension');if(dim)dim.onchange=()=>document.querySelector('#dimension-output').textContent=({Complexity:'Complexity: examine the scope and difficulty of engineering work.',Delivery:'Delivery: examine completed contributions and execution signals.',Reliability:'Reliability: examine contributions that improve system stability.'})[dim.value];
});
document.querySelector('.close-dialog').onclick=()=>dialog.close();dialog.onclick=ev=>{if(ev.target===dialog){const r=dialog.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)dialog.close();}};dialog.onclose=()=>opener?.focus();
document.querySelector('#protocol').onchange=ev=>{const val=ev.target.value;document.querySelector('#packet-output').textContent=({'Wi-Fi':'Wi-Fi · Frame → Access point → IP network','Bluetooth':'Bluetooth · Controller → Paired device → Application','Ethernet':'Ethernet · Frame → Switch → IP network'})[val];const route=document.querySelector('.packet-route');route.firstElementChild.textContent=val==='Bluetooth'?'Controller':'Device';route.children[2].textContent=val==='Bluetooth'?'Paired device':val==='Ethernet'?'Switch':'Access point';route.lastElementChild.textContent=val==='Bluetooth'?'Application':'Service';};
document.querySelector('#resume').outerHTML=link('Download Resume',Profile.resumeUrl,'text-button');
const sectionObserver=new IntersectionObserver(entries=>{for(const ent of entries)if(ent.isIntersecting)document.querySelectorAll('nav a').forEach(a=>{const active=a.hash==='#'+ent.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});},{rootMargin:'-15% 0px -60% 0px'});document.querySelectorAll('main section[id]').forEach(s=>sectionObserver.observe(s));
const countObserver=new IntersectionObserver(entries=>entries.forEach(ent=>{if(!ent.isIntersecting)return;countObserver.unobserve(ent.target);if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const label=ent.target.dataset.number,n=parseInt(label),suffix=label.replace(/[0-9]/g,''),start=performance.now();function tick(t){const f=Math.min((t-start)/900,1);ent.target.textContent=Math.round(n*(1-(1-f)**3))+suffix;if(f<1)requestAnimationFrame(tick);}requestAnimationFrame(tick);}),{threshold:.5});document.querySelectorAll('[data-number]').forEach(n=>countObserver.observe(n));
document.querySelectorAll('.featured').forEach(card=>{card.onpointermove=ev=>{if(ev.pointerType!=='mouse'||matchMedia('(prefers-reduced-motion: reduce)').matches||document.body.classList.contains('motion-paused'))return;const r=card.getBoundingClientRect();card.style.transform=`perspective(1100px) rotateX(${-(ev.clientY-r.top-r.height/2)/r.height*3}deg) rotateY(${(ev.clientX-r.left-r.width/2)/r.width*3}deg)`;};card.onpointerleave=()=>card.style.transform='';});
